### PR TITLE
Add more chip control - review only

### PR DESCRIPTION
**Pull request by gherlein**
I am not at all sure I like this approach and am only creating this PR to create a discussion.  Leaving low level radio settings on a per USB command basis seems wrong.  I am leaning towards implementing whole "profiles" of settings that can be set with one command instead of leaving so much to the developer on the host side of the USB.  A set of a half dozen modes would be much easier for MOST of the users.  I think.  WHat do you think?

### CODE REVIEW

**Comment by adjavaherian** [comment]
Greg, so does this allow the Crazy Radio to connect to any NRFL01 Rx?  I was under the impression that a lot of the TX setup was done via the Python stack and we would only have to expose some of the lower level NRF functions.  Looks like its going somewhere tho!  Awesome.

**Comment by gherlein** [comment]
Yes, the goal is to allow the CrazyRadio to communicate with any NRF25/51/52 radio configured however they are - probably on an Arduinio platform.  CrazyFlie makes a ton of assumptions on things like number of bytes of CRC, number of bytes of address, number of pipes, must use Enhanced Shockburst, etc.  My goal was to unlock all the other behavior.  BUT, I don't think exposing all the little bits to the client side to tweak seems like the right way to do it.  I think your original "modes" may be a better - let the client say "go into mode 11 please" (for example) and pick that mode from a documented chart and let the library do all the right things.  Some changes, for example, require a radio restart.  Others do not.  Exposing that complexity to the author of an app on the other side of the USB ssems like asking them to learn too much.  

But, there are some things we likely want to change on the fly - like channel for example:  think frequency agility.  I'm still exploring this chip and what can be done and what can't.

Another thing I want to expose is the ability to use the AES encryption that's built into the chip.  Another reason for "modes" and not just exposing the raw chip-level configurability.  

I'd welcome your opinion.

**Comment by adjavaherian** [comment]
Greg, sounds cool, I haven't contributed any code thus far, but I've been looking at the firmware and the radio driver and trying to suss out how we could leverage the protocol libraries here.  https://github.com/goebish/nrf24_multipro

if you haven't seen the multipro library, its pretty awesome because it supports multiple protocols for popular NRF based quads and NRF clones.

I think the difference is in the way CrazyRadio handles many of the protocol specific through the driver as opposed to building and linking them all together into the firmware?

**Comment by gherlein** [comment]
Without something in the firmware to allow a client to change address length, CRC byte length, disable/enable CRC, enable/disable enhanced shockburst then something like multipro cannot work.  There has to be at least hooks to control all those settings.

**Comment by gherlein** [comment]
One of the key things some folks may want to do with the CrazyRadio is to use sniff traffic.  For that, the https://github.com/BastilleResearch/nrf-research-firmware may be a better solution.

**Comment by ataffanel** [comment]
Thanks a lot for the PR! and sorry for the very late review.
The code look good and from what I have tested it does not break the main functionalities (ie. it still works with the Crazyflie) so it looks good to me. I have been pushing a commit cleaning-up #ifdefs (they are not needed) and two files that where pushed by mistake.
Since this is only adding functionality and not breaking anything I merge it!

**Pull request merged**
